INSERT INTO PERSONAL_OPTION (PK, OPTION_NAME) VALUES ('O0001', 'One_Shot');
INSERT INTO PERSONAL_OPTION (PK, OPTION_NAME) VALUES ('O0002', 'Two_Shot');
INSERT INTO PERSONAL_OPTION (PK, OPTION_NAME) VALUES ('O0003', 'Three_Shot');
INSERT INTO PERSONAL_OPTION (PK, OPTION_NAME) VALUES ('O0004', 'Vanilla_Syrup');
INSERT INTO PERSONAL_OPTION (PK, OPTION_NAME) VALUES ('O0005', 'Hazelnut_Syrup');

